language: python
python:
    - "2.7"
install:
    - pip install -r requirements-dev.txt
services:
    - redis-server
script:
    - python -m unittest discover
notifications:
      slack: measureofquality:JM7OHL9I5dCpVjelhBYiZ1iH
